### ISSUE TITLE
fix win compilation

### ISSUE THREAD

**Issue by agudpp** [agudpp/alias#142]
http://www.tripleboot.org/?p=138#more-138
missing `qwindows.dll` 

![image](https://user-images.githubusercontent.com/1697015/101089311-47823380-35b5-11eb-995d-147fb6425335.png)

**Comment by agudpp** [comment]
to solve this basically we needed to add a `platforms/` folder where the binary is and put copy the qwindows.dll from the qt. its already fixed

**Comment by strider29** [comment]
Good job
